# These types of DB containers use the publicly available Docker image
postgresql.container.image=postgres

# These types of DB containers must use a custom Camunda Docker image
# as they require a non-default Transaction Isolation level setup
mysql.container.image=registry.cadenzaflow.cloud/team-cambpm/cadenzaflow-ci-mysql
mssql.container.image=registry.cadenzaflow.cloud/team-cambpm/cadenzaflow-ci-sqlserver

# These types of DB containers are currently not supported
#db2.container.image=registry.cadenzaflow.cloud/team-cambpm/cadenzaflow-ci-db2
#oracle.container.image=registry.cadenzaflow.cloud/team-cambpm/cadenzaflow-ci-oracle:18
