blank_issues_enabled: false
contact_links:
  - name: User Forum
    url: https://forum.cadenzaflow.io/
    about: Ask questions about using CadenzaFlow Platform here.
  - name: Enterprise Support
    url: https://cadenzaflow.com/services/enterprise-support-guide/
    about: As an enterprise customer, contact our product support here.